---
- name: "Configure the EKS cluster with kubectl"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  roles:
    - deploy
    - configure-server