---
- name: "Install dependencies"
  hosts: all
  user: ubuntu
  gather_facts: false
  become: yes
  pre_tasks:
    - name: Add SSH host key to known_hosts
      known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ hostvars[inventory_hostname]['ansible_ssh_host_key'] }}"
    - name: "update apt packages."
      apt:
        update_cache: yes

    - name: "upgrade packages"
      apt:
        upgrade: yes

    - name: remove stale dependencies
      apt:
        autoremove: yes

    - name: "install node 13.X"
      shell: |
        curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
        sudo apt -y upgrade
        sudo apt install -y nodejs

    - name: "Install zip utility."
      apt:
        name: [ "zip", "unzip" ]
        state: latest
        update_cache: yes
        
    - name: "install pm2 by npm"
      become: true
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

  roles:
    - install-kubectl

- name: "Fetch kubectl config"
  hosts: all
  user: ubuntu
  gather_facts: false

  become: yes
  vars:
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  pre_tasks:
    - name: Create a kubeconfig file for the cluster
      shell: "aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name {{ ENVIRONMENT_NAME }}-cluster-${{ CIRCLE_WORKFLOW_ID:0:7 }}"