- name: "Deploy latest app"
  hosts: all
  user: ubuntu
  gather_facts: false
  become: true
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  tasks:
    - name: Update the deployment to run the latest Build
      shell: "./bin/kubectl set image deployments/{{ ENVIRONMENT_NAME }}-deployment {{ ENVIRONMENT_NAME }}=oyewoas/{{ ENVIRONMENT_NAME }}:{{ CIRCLE_WORKFLOW_ID:0:7 }}"
      args:
        chdir: $HOME

    - name: Check if deployment it is successful
      shell: "./bin/kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}-deployment"
      args:
        chdir: $HOME