---
- name: "Persist LoadBalancer's DNS name locally"
  hosts: all
  user: ubuntu
  gather_facts: false
  environment:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  tasks:
    - name: Get the LoadBalancer's DNS name
      shell: "./bin/kubectl get svc {{ ENVIRONMENT_NAME }}-server"
      register: elb_dns
      args:
        chdir: $HOME

    - name: Copy the output to a local file
      copy:
        content: "{{ elb_dns.stdout }}"
        dest: "../outputs/elb-dns.txt"
      delegate_to: localhost