- name: Copy server configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-server.yml"
    dest: $HOME

- name: Create server configuration
  command: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-server.yml"
  args:
    chdir: $HOME