Description: >
  Ayooluwa Oyewo - Capstone Project to Create two individual hosts to manage the EKS Cluster

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone-project
    Type: String
  SSHKeyName:
    Description: SSH key for access
    Default: udacity
    Type: String
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-00c39f71452c08778
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-mgt-SG-${WorkflowID}
      GroupDescription: Allow port 22 and 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  mgtHost1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-mgt1-${WorkflowID}
        - Key: Project
          Value: !Ref EnvironmentName

  mgtHost2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref amiImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-mgt2-${WorkflowID}
        - Key: Project
          Value: !Ref EnvironmentName
