- name: Copy deployment configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yaml"
    dest: "/home/ubuntu"

- name: Execute kubectl apply
  shell: "{{ kubectl_path }} apply -f {{ ENVIRONMENT_NAME }}-deployment.yaml --kubeconfig=~/.kube/config"
  args:
    chdir: "/home/ubuntu"