apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-project-server
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80