apiVersion: v1
kind: Service
metadata:
  name: starwars-directory-server
spec:
  type: LoadBalancer
  selector:
    app: starwars-directory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080