---
- name: Download kubectl binary
  become: true
  get_url:
    url: "https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: "u+x"

- name: Apply execute permissions to the binary
  become: true
  command: chmod +x /usr/local/bin/kubectl

- name: Configure kubectl path
  become: true
  lineinfile:
    path: "/home/ubuntu/.bashrc"
    line: "export PATH=$PATH:/usr/local/bin"
    insertafter: EOF
    state: present

- name: Source the bashrc file
  shell: source "/home/ubuntu/.bashrc"
  args:
    executable: /bin/bash
  changed_when: false
