- name: Copy service configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-service.yaml"
    dest: "/home/ubuntu"

- name: Create service configuration
  shell: "{{ kubectl_path }} apply -f {{ ENVIRONMENT_NAME }}-service.yaml --kubeconfig=/home/ubuntu/.kube/config"
  args:
    chdir: "/home/ubuntu"
