- name: Copy service configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-service.yaml"
    dest: $HOME

- name: Create service configuration
  shell: "{{ kubectl_path }} apply -f {{ ENVIRONMENT_NAME }}-service.yaml"
  args:
    chdir: $HOME
