- name: Copy service configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-service.yaml"
    dest: "/home/ubuntu"

- name: Create service configuration
  shell: "{{ kubectl_path }} apply -f {{ ENVIRONMENT_NAME }}-service.yaml --kubeconfig=/home/ubuntu/.kube/config --aws-access-key-id={{ AWS_ACCESS_KEY_ID }} --aws-secret-access-key={{ AWS_SECRET_ACCESS_KEY }} --aws-region={{ AWS_DEFAULT_REGION }}"
  args:
    chdir: "/home/ubuntu"
